-- 001_migration.schema.sql

CREATE TABLE IF NOT EXISTS goq_migrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    hash TEXT NOT NULL,
    applied DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
