// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration.sql

package store

import (
	"context"
)

const createGoqMigrationTable = `-- name: CreateGoqMigrationTable :exec
CREATE TABLE IF NOT EXISTS goq_migrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    hash TEXT NOT NULL,
    applied DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
`

func (q *Queries) CreateGoqMigrationTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createGoqMigrationTable)
	return err
}

const getGoqMigration = `-- name: GetGoqMigration :one
SELECT id, name, hash, applied
FROM goq_migrations
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetGoqMigration(ctx context.Context, name string) (GoqMigration, error) {
	row := q.db.QueryRowContext(ctx, getGoqMigration, name)
	var i GoqMigration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hash,
		&i.Applied,
	)
	return i, err
}

const upsertGoqMigration = `-- name: UpsertGoqMigration :exec
INSERT INTO goq_migrations (name, hash)
VALUES (?, ?)
ON CONFLICT(name) DO UPDATE SET
    hash = excluded.hash, 
    applied = CURRENT_TIMESTAMP
`

type UpsertGoqMigrationParams struct {
	Name string `json:"name"`
	Hash string `json:"hash"`
}

func (q *Queries) UpsertGoqMigration(ctx context.Context, arg UpsertGoqMigrationParams) error {
	_, err := q.db.ExecContext(ctx, upsertGoqMigration, arg.Name, arg.Hash)
	return err
}
