// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type GoqMigration struct {
	ID      int64     `json:"id"`
	Name    string    `json:"name"`
	Hash    string    `json:"hash"`
	Applied time.Time `json:"applied"`
}

type Topic struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	RetentionMs   sql.NullInt64  `json:"retention_ms"`
	CleanupPolicy sql.NullString `json:"cleanup_policy"`
	CreatedAt     time.Time      `json:"created_at"`
}
