// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateGoqMigrationTable(ctx context.Context) error
	GetGoqMigration(ctx context.Context, name string) (GoqMigration, error)
	GetTopic(ctx context.Context, name string) (Topic, error)
	UpsertGoqMigration(ctx context.Context, arg UpsertGoqMigrationParams) error
	UpsertTopic(ctx context.Context, arg UpsertTopicParams) error
}

var _ Querier = (*Queries)(nil)
