// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package store

import (
	"context"
	"database/sql"
)

const getTopic = `-- name: GetTopic :one
SELECT id, name, retention_ms, cleanup_policy, created_at
FROM topic
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetTopic(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopic, name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RetentionMs,
		&i.CleanupPolicy,
		&i.CreatedAt,
	)
	return i, err
}

const upsertTopic = `-- name: UpsertTopic :exec
INSERT INTO topic (name, retention_ms, cleanup_policy)
VALUES (?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    retention_ms = excluded.retention_ms,
    cleanup_policy = excluded.cleanup_policy
`

type UpsertTopicParams struct {
	Name          string         `json:"name"`
	RetentionMs   sql.NullInt64  `json:"retention_ms"`
	CleanupPolicy sql.NullString `json:"cleanup_policy"`
}

func (q *Queries) UpsertTopic(ctx context.Context, arg UpsertTopicParams) error {
	_, err := q.db.ExecContext(ctx, upsertTopic, arg.Name, arg.RetentionMs, arg.CleanupPolicy)
	return err
}
